server.port=8081
server.connection-timeout=5000
# Zmniejszenie limitu keep-alive wymusi na przeglądarce częstsze odświeżanie sesji
server.tomcat.keep-alive-timeout=5000
server.tomcat.max-keep-alive-requests=10